POST http://localhost:5000/send-email
Content-Type: application/json
Authorization: Bearer 907d762a1c454c5d9a59f9825e36d40c

{
    "Name": "John Doe",
    "Email": "john.doe@example.com",
    "Message": "Hello, this is a test message.",
    "client_IP": "172.59.71.52"
}
